maykinmedia/referentielijsten

.github/workflows/ci.yml
fixed issue where docker image workflow gets skipped when merged to master
=> :bug: fixed docker image push when merged to master

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, src/referentielijsten/api/admin.py, src/referentielijsten/conf/base.py
=> :sparkles:[#13] add import export to item admin

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Fixes [#50](https://github.com/maykinmedia/open-api-framework/issues/50)
=> :arrow_up: [#50] upgrade django version

Dockerfile, requirements/ci.txt, requirements/dev.txt
Fixes #23 
**Changes**
upgrade webob from 1.8.7 to 1.8.8
=> :arrow_up: [#50] upgrade webob from 1.8.7 to 1.8.8

Dockerfile
Fixes #23 
**Changes**
Update setuptools in Dockerfile
=> :sparkles: [#50] ensured that setuptools is version 70 or higher in Dockerfile

Dockerfile
=> :bug: [#50] moved setuptools installation in dockerfile

Dockerfile
=> :bug: [#50] update pip in stage 3 of dockerfile

package-lock.json
=> :arrow_up: [#50] fixed npm vunerabilities

.bumpversion.cfg, CHANGELOG.rst, README.EN.rst, README.rst, package.json, src/referentielijsten/__init__.py
Fixes  maykinmedia/open-api-framework#80 (referentielijsten part)
=> :memo:release 0.2.0

.github/workflows/ci.yml, docs/conf.py
Fixes maykinmedia/open-api-framework#92 partially
**Changes**
* Make sure docs are built in CI
=> :construction_worker: [maykinmedia/open-api-framework#92] Make sure docs are built in CI

.github/workflows/ci.yml
Fixes maykinmedia/open-api-framework#92 partially
Forgot to update this in the previous PR :facepalm:
=> :construction_worker: [maykinmedia/open-api-framework#92] Fix docker latest tag publish

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Fixes maykinmedia/open-api-framework#93 partially
**Changes**
* Security updates
=> :arrow_up: [maykinmedia/open-api-framework#93] Security updates

.readthedocs.yaml
to make sure the docs are published there
=> :wrench: Add configuration for readthedocs

src/referentielijsten/urls.py
Fixes: https://github.com/maykinmedia/open-api-framework/issues/79
**Changes**
disable admin nav sidebar
=> [maykinmedia/open-api-framework#79] disable admin nav sidebar

.github/workflows/quick-start.yml, README.EN.rst, README.rst
Fixes [maykinmedia/open-api-framework#102]
**Changes**
[Describe the changes here]
=> [maykinmedia/open-api-framework#102] Add quick-start.yml

Dockerfile, bin/docker_start.sh, bin/load_fixtures.sh
Fixes #55
**Changes**
* Load fixtures automatically in docker
=> :whale: [#55] Load fixtures automatically in docker

.github/workflows/ci.yml, .github/workflows/code-quality.yml, .github/workflows/codeql-analysis.yml, .github/workflows/generate-postman-collection.yml, .github/workflows/generate-sdks.yml, .github/workflows/lint-oas.yml, .github/workflows/oaf-check.yml, .github/workflows/oas-check.yml, .github/workflows/quick-start.yml, CHANGELOG.rst, docker-compose.yml, docker-init-db.sql, requirements/ci.txt, requirements/dev.txt
Fixes maykinmedia/open-api-framework#117
**Changes**
* Upgrade postgres to 17
* Upgrade black/flake8/isort
* Upgrade github actions versions
* Upgrade nodejs in CI to 20
=> ⬆️ [maykinmedia/open-api-framework#117] Upgrade dependencies

.bumpversion.cfg, CHANGELOG.rst, README.EN.rst, README.rst, package-lock.json, package.json, src/referentielijsten/__init__.py, src/referentielijsten/conf/locale/nl/LC_MESSAGES/django.po
Fixes #64
**Changes**
* Release version 0.3.1
=> :bookmark: Release version 0.3.1

src/referentielijsten/api/admin.py
Fixes #71
**Changes**
Added item inline to table model in admin
=> :sparkles: [#71] add item inline to table

.bumpversion.cfg, CHANGELOG.rst, README.EN.rst, README.rst, package-lock.json, package.json, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, src/referentielijsten/__init__.py
=> :bookmark: Release 0.4.0

src/referentielijsten/scss/admin/_admin_theme.scss, src/referentielijsten/scss/admin/_app_overrides.scss, src/referentielijsten/scss/admin/_vars.scss, src/referentielijsten/scss/admin/themes/_dark.scss, src/referentielijsten/scss/admin/themes/_light.scss, src/referentielijsten/templates/admin/base_site.html
Fixes #https://github.com/maykinmedia/open-api-framework/issues/149
**Changes**
Fixed light/dark theme in admin UI with the missing toggle.
=> :lipstick: Fix light/dark themes for admin
